export const GET_ALL_GENRES_REQUEST = "GET_ALL_GENRES_REQUEST";
export const GET_ALL_GENRES_SUCCESS = "GET_ALL_GENRES_SUCCESS";
export const GET_ALL_GENRES_FAIL = "GET_ALL_GENRES_FAIL";
export const GET_ALL_GENRES_RESET = "GET_ALL_GENRES_RESET";

export const GET_NO_EXTEND_GENRES_REQUEST = "GET_NO_EXTEND_GENRES_REQUEST";
export const GET_NO_EXTEND_GENRES_SUCCESS = "GET_NO_EXTEND_GENRES_SUCCESS";
export const GET_NO_EXTEND_GENRES_FAIL = "GET_NO_EXTEND_GENRES_FAIL";

export const GET_EXTEND_GENRES_REQUEST = "GET_EXTEND_GENRES_REQUEST";
export const GET_EXTEND_GENRES_SUCCESS = "GET_EXTEND_GENRES_SUCCESS";
export const GET_EXTEND_GENRES_FAIL = "GET_EXTEND_GENRES_FAIL";

export const CREATE_GENRE_REQUEST = "CREATE_GENRE_REQUEST";
export const CREATE_GENRE_SUCCESS = "CREATE_GENRE_SUCCESS";
export const CREATE_GENRE_FAIL = "CREATE_GENRE_FAIL";
export const CREATE_GENRE_RESET = "CREATE_GENRE_RESET";

export const UPDATE_GENRE_REQUEST = "UPDATE_GENRE_REQUEST";
export const UPDATE_GENRE_SUCCESS = "UPDATE_GENRE_SUCCESS";
export const UPDATE_GENRE_FAIL = "UPDATE_GENRE_FAIL";
export const UPDATE_GENRE_RESET = "UPDATE_GENRE_RESET";

export const DELETE_GENRE_REQUEST = "DELETE_GENRE_REQUEST";
export const DELETE_GENRE_SUCCESS = "DELETE_GENRE_SUCCESS";
export const DELETE_GENRE_FAIL = "DELETE_GENRE_FAIL";
export const DELETE_GENRE_RESET = "DELETE_GENRE_RESET";

export const ENABLE_GENRE_REQUEST = "ENABLE_GENRE_REQUEST";
export const ENABLE_GENRE_SUCCESS = "ENABLE_GENRE_SUCCESS";
export const ENABLE_GENRE_FAIL = "ENABLE_GENRE_FAIL";
export const ENABLE_GENRE_RESET = "ENABLE_GENRE_RESET";
