export const MANGAS_RECOMMEND_REQUEST = "MANGAS_RECOMMEND_REQUEST";
export const MANGAS_RECOMMEND_SUCCESS = "MANGAS_RECOMMEND_SUCCESS";
export const MANGAS_RECOMMEND_FAIL = "MANGAS_RECOMMEND_FAIL";

export const MANGAS_COLLECTION_REQUEST = "MANGAS_COLLECTION_REQUEST";
export const MANGAS_COLLECTION_SUCCESS = "MANGAS_COLLECTION_SUCCESS";
export const MANGAS_COLLECTION_FAIL = "MANGAS_COLLECTION_FAIL";
export const MANGAS_COLLECTION_RESET = "MANGAS_COLLECTION_RESET";

export const MANGAS_HOT_REQUEST = "MANGAS_HOT_REQUEST";
export const MANGAS_HOT_SUCCESS = "MANGAS_HOT_SUCCESS";
export const MANGAS_HOT_FAIL = "MANGAS_HOT_FAIL";

export const MANGAS_NEW_WEEK_REQUEST = "MANGAS_NEW_WEEK_REQUEST";
export const MANGAS_NEW_WEEK_SUCCESS = "MANGAS_NEW_WEEK_SUCCESS";
export const MANGAS_NEW_WEEK_FAIL = "MANGAS_NEW_WEEK_FAIL";

export const MANGAS_NEW_UPDATE_REQUEST = "MANGAS_NEW_UPDATE_REQUEST";
export const MANGAS_NEW_UPDATE_SUCCESS = "MANGAS_NEW_UPDATE_SUCCESS";
export const MANGAS_NEW_UPDATE_FAIL = "MANGAS_NEW_UPDATE_FAIL";

export const MANGAS_GENRE_REQUEST = "MANGAS_GENRE_REQUEST";
export const MANGAS_GENRE_SUCCESS = "MANGAS_GENRE_SUCCESS";
export const MANGAS_GENRE_FAIL = "MANGAS_GENRE_FAIL";

export const MANGAS_ASEARCH_REQUEST = "MANGAS_ASEARCH_REQUEST";
export const MANGAS_ASEARCH_SUCCESS = "MANGAS_ASEARCH_SUCCESS";
export const MANGAS_ASEARCH_FAIL = "MANGAS_ASEARCH_FAIL";

export const MANGAS_KEYWORD_REQUEST = "MANGAS_KEYWORD_REQUEST";
export const MANGAS_KEYWORD_SUCCESS = "MANGAS_KEYWORD_SUCCESS";
export const MANGAS_KEYWORD_FAIL = "MANGAS_KEYWORD_FAIL";

export const MANGAS_GENDER_REQUEST = "MANGAS_GENDER_REQUEST";
export const MANGAS_GENDER_SUCCESS = "MANGAS_GENDER_SUCCESS";
export const MANGAS_GENDER_FAIL = "MANGAS_GENDER_FAIL";

export const MANGAS_TOP_MONTH_REQUEST = "MANGAS_TOP_MONTH_REQUEST";
export const MANGAS_TOP_MONTH_SUCCESS = "MANGAS_TOP_MONTH_SUCCESS";
export const MANGAS_TOP_MONTH_FAIL = "MANGAS_TOP_MONTH_FAIL";

export const MANGAS_HISTORY_REQUEST = "MANGAS_HISTORY_REQUEST";
export const MANGAS_HISTORY_SUCCESS = "MANGAS_HISTORY_SUCCESS";
export const MANGAS_HISTORY_FAIL = "MANGAS_HISTORY_FAIL";
export const MANGAS_HISTORY_RESET = "MANGAS_HISTORY_RESET";

export const ADD_HISTORY_REQUEST = "ADD_HISTORY_REQUEST";
export const ADD_HISTORY_SUCCESS = "ADD_HISTORY_SUCCESS";
export const ADD_HISTORY_FAIL = "ADD_HISTORY_FAIL";
export const ADD_HISTORY_RESET = "ADD_HISTORY_RESET";

export const DELETE_HISTORY_REQUEST = "DELETE_HISTORY_REQUEST";
export const DELETE_HISTORY_SUCCESS = "DELETE_HISTORY_SUCCESS";
export const DELETE_HISTORY_FAIL = "DELETE_HISTORY_FAIL";
export const DELETE_HISTORY_RESET = "DELETE_HISTORY_RESET";

export const MANGA_DETAILS_REQUEST = "MANGA_DETAILS_REQUEST";
export const MANGA_DETAILS_SUCCESS = "MANGA_DETAILS_SUCCESS";
export const MANGA_DETAILS_FAIL = "MANGA_DETAILS_FAIL";
export const MANGA_DETAILS_RESET = "MANGA_DETAILS_RESET";

export const CHAPTER_DETAILS_REQUEST = "CHAPTER_DETAILS_REQUEST";
export const CHAPTER_DETAILS_SUCCESS = "CHAPTER_DETAILS_SUCCESS";
export const CHAPTER_DETAILS_FAIL = "CHAPTER_DETAILS_FAIL";
export const CHAPTER_DETAILS_RESET = "CHAPTER_DETAILS_RESET";

export const RATING_MANGA_REQUEST = "RATING_MANGA_REQUEST";
export const RATING_MANGA_SUCCESS = "RATING_MANGA_SUCCESS";
export const RATING_MANGA_FAIL = "RATING_MANGA_FAIL";
export const RATING_MANGA_RESET = "RATING_MANGA_RESET";

export const GET_RATING_MANGA_REQUEST = "GET_RATING_MANGA_REQUEST";
export const GET_RATING_MANGA_SUCCESS = "GET_RATING_MANGA_SUCCESS";
export const GET_RATING_MANGA_FAIL = "GET_RATING_MANGA_FAIL";
export const GET_RATING_MANGA_RESET = "GET_RATING_MANGA_RESET";

export const MANGA_COMMENTS_REQUEST = "MANGA_COMMENTS_REQUEST";
export const MANGA_COMMENTS_SUCCESS = "MANGA_COMMENTS_SUCCESS";
export const MANGA_COMMENTS_FAIL = "MANGA_COMMENTS_FAIL";
export const MANGA_COMMENTS_RESET = "MANGA_COMMENTS_RESET";

export const CHAPTER_COMMENTS_REQUEST = "CHAPTER_COMMENTS_REQUEST";
export const CHAPTER_COMMENTS_SUCCESS = "CHAPTER_COMMENTS_SUCCESS";
export const CHAPTER_COMMENTS_FAIL = "CHAPTER_COMMENTS_FAIL";
export const CHAPTER_COMMENTS_RESET = "CHAPTER_COMMENTS_RESET";

export const CREATE_COMMNENT_REQUEST = "CREATE_COMMNENT_REQUEST";
export const CREATE_COMMNENT_SUCCESS = "CREATE_COMMNENT_SUCCESS";
export const CREATE_COMMNENT_FAIL = "CREATE_COMMNENT_FAIL";
export const CREATE_COMMNENT_RESET = "CREATE_COMMNENT_RESET";

export const EMO_COMMNENT_REQUEST = "EMO_COMMNENT_REQUEST";
export const EMO_COMMNENT_SUCCESS = "EMO_COMMNENT_SUCCESS";
export const EMO_COMMNENT_FAIL = "EMO_COMMNENT_FAIL";
export const EMO_COMMNENT_RESET = "EMO_COMMNENT_RESET";

export const CREATE_FEEDBACK_REQUEST = "CREATE_FEEDBACK_REQUEST";
export const CREATE_FEEDBACK_SUCCESS = "CREATE_FEEDBACK_SUCCESS";
export const CREATE_FEEDBACK_FAIL = "CREATE_FEEDBACK_FAIL";
export const CREATE_FEEDBACK_RESET = "CREATE_FEEDBACK_RESET";

export const EMO_FEEDBACK_REQUEST = "EMO_FEEDBACK_REQUEST";
export const EMO_FEEDBACK_SUCCESS = "EMO_FEEDBACK_SUCCESS";
export const EMO_FEEDBACK_FAIL = "EMO_FEEDBACK_FAIL";
export const EMO_FEEDBACK_RESET = "EMO_FEEDBACK_RESET";

export const ALL_MANGA_MANAGER_REQUEST = "ALL_MANGA_MANAGER_REQUEST";
export const ALL_MANGA_MANAGER_SUCCESS = "ALL_MANGA_MANAGER_SUCCESS";
export const ALL_MANGA_MANAGER_FAIL = "ALL_MANGA_MANAGER_FAIL";
export const ALL_MANGA_MANAGER_RESET = "ALL_MANGA_MANAGER_RESET";

export const MANGAS_MANAGER_REQUEST = "MANGAS_MANAGER_REQUEST";
export const MANGAS_MANAGER_SUCCESS = "MANGAS_MANAGER_SUCCESS";
export const MANGAS_MANAGER_FAIL = "MANGAS_MANAGER_FAIL";
export const MANGAS_MANAGER_RESET = "MANGAS_MANAGER_RESET";

export const MANGAS_JOIN_UP_REQUEST = "MANGAS_JOIN_UP_REQUEST";
export const MANGAS_JOIN_UP_SUCCESS = "MANGAS_JOIN_UP_SUCCESS";
export const MANGAS_JOIN_UP_FAIL = "MANGAS_JOIN_UP_FAIL";
export const MANGAS_JOIN_UP_RESET = "MANGAS_JOIN_UP_RESET";

export const CREATE_MANGA_REQUEST = "CREATE_MANGA_REQUEST";
export const CREATE_MANGA_SUCCESS = "CREATE_MANGA_SUCCESS";
export const CREATE_MANGA_FAIL = "CREATE_MANGA_FAIL";
export const CREATE_MANGA_RESET = "CREATE_MANGA_RESET";

export const GET_MANGA_INFO_REQUEST = "GET_MANGA_INFO_REQUEST";
export const GET_MANGA_INFO_SUCCESS = "GET_MANGA_INFO_SUCCESS";
export const GET_MANGA_INFO_FAIL = "GET_MANGA_INFO_FAIL";
export const GET_MANGA_INFO_RESET = "GET_MANGA_INFO_RESET";

export const UPDATE_MANGA_REQUEST = "UPDATE_MANGA_REQUEST";
export const UPDATE_MANGA_SUCCESS = "UPDATE_MANGA_SUCCESS";
export const UPDATE_MANGA_FAIL = "UPDATE_MANGA_FAIL";
export const UPDATE_MANGA_RESET = "UPDATE_MANGA_RESET";

export const DELETE_MANGAS_REQUEST = "DELETE_MANGAS_REQUEST";
export const DELETE_MANGAS_SUCCESS = "DELETE_MANGAS_SUCCESS";
export const DELETE_MANGAS_FAIL = "DELETE_MANGAS_FAIL";
export const DELETE_MANGAS_RESET = "DELETE_MANGAS_RESET";

export const ENABLE_MANGA_REQUEST = "ENABLE_MANGA_REQUEST";
export const ENABLE_MANGA_SUCCESS = "ENABLE_MANGA_SUCCESS";
export const ENABLE_MANGA_FAIL = "ENABLE_MANGA_FAIL";
export const ENABLE_MANGA_RESET = "ENABLE_MANGA_RESET";

export const GET_LIST_USERS_REQUEST = "GET_LIST_USERS_REQUEST";
export const GET_LIST_USERS_SUCCESS = "GET_LIST_USERS_SUCCESS";
export const GET_LIST_USERS_FAIL = "GET_LIST_USERS_FAIL";
export const GET_LIST_USERS_RESET = "GET_LIST_USERS_RESET";

export const ADD_MEMBERS_REQUEST = "ADD_MEMBERS_REQUEST";
export const ADD_MEMBERS_SUCCESS = "ADD_MEMBERS_SUCCESS";
export const ADD_MEMBERS_FAIL = "ADD_MEMBERS_FAIL";
export const ADD_MEMBERS_RESET = "ADD_MEMBERS_RESET";

export const TRANSFER_OF_OWNERSHIP_REQUEST = "TRANSFER_OF_OWNERSHIP_REQUEST";
export const TRANSFER_OF_OWNERSHIP_SUCCESS = "TRANSFER_OF_OWNERSHIP_SUCCESS";
export const TRANSFER_OF_OWNERSHIP_FAIL = "TRANSFER_OF_OWNERSHIP_FAIL";
export const TRANSFER_OF_OWNERSHIP_RESET = "TRANSFER_OF_OWNERSHIP_RESET";

export const CHAPTERS_MANAGER_REQUEST = "MANGAS_MANAGER_REQUEST";
export const CHAPTERS_MANAGER_SUCCESS = "MANGAS_MANAGER_SUCCESS";
export const CHAPTERS_MANAGER_FAIL = "MANGAS_MANAGER_FAIL";
export const CHAPTERS_MANAGER_RESET = "MANGAS_MANAGER_RESET";

export const CREATE_CHAPTER_REQUEST = "CREATE_CHAPTER_REQUEST";
export const CREATE_CHAPTER_SUCCESS = "CREATE_CHAPTER_SUCCESS";
export const CREATE_CHAPTER_FAIL = "CREATE_CHAPTER_FAIL";
export const CREATE_CHAPTER_RESET = "CREATE_CHAPTER_RESET";

export const GET_CHAPTER_INFO_REQUEST = "GET_CHAPTER_INFO_REQUEST";
export const GET_CHAPTER_INFO_SUCCESS = "GET_CHAPTER_INFO_SUCCESS";
export const GET_CHAPTER_INFO_FAIL = "GET_CHAPTER_INFO_FAIL";
export const GET_CHAPTER_INFO_RESET = "GET_CHAPTER_INFO_RESET";

export const UPDATE_CHAPTER_REQUEST = "UPDATE_CHAPTER_REQUEST";
export const UPDATE_CHAPTER_SUCCESS = "UPDATE_CHAPTER_SUCCESS";
export const UPDATE_CHAPTER_FAIL = "UPDATE_CHAPTER_FAIL";
export const UPDATE_CHAPTER_RESET = "UPDATE_CHAPTER_RESET";

export const DELETE_CHAPTERS_REQUEST = "DELETE_MANGAS_REQUEST";
export const DELETE_CHAPTERS_SUCCESS = "DELETE_MANGAS_SUCCESS";
export const DELETE_CHAPTERS_FAIL = "DELETE_MANGAS_FAIL";
export const DELETE_CHAPTERS_RESET = "DELETE_MANGAS_RESET";

export const ENABLE_CHAPTER_REQUEST = "ENABLE_MANGA_REQUEST";
export const ENABLE_CHAPTER_SUCCESS = "ENABLE_MANGA_SUCCESS";
export const ENABLE_CHAPTER_FAIL = "ENABLE_MANGA_FAIL";
export const ENABLE_CHAPTER_RESET = "ENABLE_MANGA_RESET";
