export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_GOOGLE_LOGIN_REQUEST = "USER_GOOGLE_LOGIN_REQUEST";
export const USER_GOOGLE_LOGIN_SUCCESS = "USER_GOOGLE_LOGIN_SUCCESS";
export const USER_GOOGLE_LOGIN_FAIL = "USER_GOOGLE_LOGIN_FAIL";
export const USER_GOOGLE_LOGIN_RESET = "USER_GOOGLE_LOGIN_RESET";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_RESENDEMAILVERIFICATIONTOKEN_REQUEST =
  "USER_RESENDEMAILVERIFICATIONTOKEN_REQUEST";
export const USER_RESENDEMAILVERIFICATIONTOKEN_SUCCESS =
  "USER_RESENDEMAILVERIFICATIONTOKEN_SUCCESS";
export const USER_RESENDEMAILVERIFICATIONTOKEN_FAIL =
  "USER_RESENDEMAILVERIFICATIONTOKEN_FAIL";
export const USER_RESENDEMAILVERIFICATIONTOKEN_RESET =
  "USER_RESENDEMAILVERIFICATIONTOKEN_RESET";

export const USER_VERIFYEMAIL_REQUEST = "USER_VERIFYEMAIL_REQUEST";
export const USER_VERIFYEMAIL_SUCCESS = "USER_VERIFYEMAIL_SUCCESS";
export const USER_VERIFYEMAIL_FAIL = "USER_VERIFYEMAIL_FAIL";
export const USER_VERIFYEMAIL_RESET = "USER_VERIFYEMAIL_RESET";

export const USER_RECOVER_PASSWORD_REQUEST = "USER_RECOVER_PASSWORD_REQUEST";
export const USER_RECOVER_PASSWORD_SUCCESS = "USER_RECOVER_PASSWORD_SUCCESS";
export const USER_RECOVER_PASSWORD_FAIL = "USER_RECOVER_PASSWORD_FAIL";
export const USER_RECOVER_PASSWORD_RESET = "USER_RECOVER_PASSWORD_RESET";

export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST";
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL";
export const USER_RESET_PASSWORD_RESET = "USER_RESET_PASSWORD_RESET";

export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAIL = "USER_INFO_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL";
export const USER_CHANGE_PASSWORD_RESET = "USER_CHANGE_PASSWORD_RESET";

export const USER_CREATE_PASSWORD_REQUEST = "USER_CREATE_PASSWORD_REQUEST";
export const USER_CREATE_PASSWORD_SUCCESS = "USER_CREATE_PASSWORD_SUCCESS";
export const USER_CREATE_PASSWORD_FAIL = "USER_CREATE_PASSWORD_FAIL";
export const USER_CREATE_PASSWORD_RESET = "USER_CREATE_PASSWORD_RESET";

export const GET_FOLLOW_MANGAS_REQUEST = "GET_FOLLOW_MANGAS_REQUEST";
export const GET_FOLLOW_MANGAS_SUCCESS = "GET_FOLLOW_MANGAS_SUCCESS";
export const GET_FOLLOW_MANGAS_FAIL = "GET_FOLLOW_MANGAS_FAIL";
export const GET_FOLLOW_MANGAS_RESET = "GET_FOLLOW_MANGAS_RESET";

export const GET_ALL_FOLLOW_MANGAS_REQUEST = "GET_ALL_FOLLOW_MANGAS_REQUEST";
export const GET_ALL_FOLLOW_MANGAS_SUCCESS = "GET_ALL_FOLLOW_MANGAS_SUCCESS";
export const GET_ALL_FOLLOW_MANGAS_FAIL = "GET_ALL_FOLLOW_MANGAS_FAIL";
export const GET_ALL_FOLLOW_MANGAS_RESET = "GET_ALL_FOLLOW_MANGAS_RESET";

export const GET_COMMENT_MANGAS_REQUEST = "GET_COMMENT_MANGAS_REQUEST";
export const GET_COMMENT_MANGAS_SUCCESS = "GET_COMMENT_MANGAS_SUCCESS";
export const GET_COMMENT_MANGAS_FAIL = "GET_COMMENT_MANGAS_FAIL";
export const GET_COMMENT_MANGAS_RESET = "GET_COMMENT_MANGAS_RESET";

export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAIL = "GET_NOTIFICATION_FAIL";
export const GET_NOTIFICATION_RESET = "GET_NOTIFICATION_RESET";

export const GET_NOTIFICATION_IS_READ_REQUEST =
  "GET_NOTIFICATION_IS_READ_REQUEST";
export const GET_NOTIFICATION_IS_READ_SUCCESS =
  "GET_NOTIFICATION_IS_READ_SUCCESS";
export const GET_NOTIFICATION_IS_READ_FAIL = "GET_NOTIFICATION_IS_READ_FAIL";
export const GET_NOTIFICATION_IS_READ_RESET = "GET_NOTIFICATION_IS_READ_RESET";

export const HIDDEN_NOTIFICATION_REQUEST = "HIDDEN_NOTIFICATION_REQUEST";
export const HIDDEN_NOTIFICATION_SUCCESS = "HIDDEN_NOTIFICATION_SUCCESS";
export const HIDDEN_NOTIFICATION_FAIL = "HIDDEN_NOTIFICATION_FAIL";
export const HIDDEN_NOTIFICATION_RESET = "HIDDEN_NOTIFICATION_RESET";

export const SEEN_NOTIFICATION_REQUEST = "SEEN_NOTIFICATION_REQUEST";
export const SEEN_NOTIFICATION_SUCCESS = "SEEN_NOTIFICATION_SUCCESS";
export const SEEN_NOTIFICATION_FAIL = "SEEN_NOTIFICATION_FAIL";
export const SEEN_NOTIFICATION_RESET = "SEEN_NOTIFICATION_RESET";

export const GET_DATA_READ_REQUEST = "GET_DATA_READ_REQUEST";
export const GET_DATA_READ_SUCCESS = "GET_DATA_READ_SUCCESS";
export const GET_DATA_READ_FAIL = "GET_DATA_READ_FAIL";
export const GET_DATA_READ_RESET = "GET_DATA_READ_RESET";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
export const GET_ALL_USERS_RESET = "GET_ALL_USERS_RESET";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const ENABLE_USER_REQUEST = "DELETE_USER_REQUEST";
export const ENABLE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const ENABLE_USER_FAIL = "DELETE_USER_FAIL";
export const ENABLE_USER_RESET = "DELETE_USER_RESET";

export const SET_ADMIN_USER_REQUEST = "SET_ADMIN_USER_REQUEST";
export const SET_ADMIN_USER_SUCCESS = "SET_ADMIN_USER_SUCCESS";
export const SET_ADMIN_USER_FAIL = "SET_ADMIN_USER_FAIL";
export const SET_ADMIN_USER_RESET = "SET_ADMIN_USER_RESET";

export const AUTO_TIME_READ_REQUEST = "AUTO_TIME_READ_REQUEST";
export const AUTO_TIME_READ_SUCCESS = "AUTO_TIME_READ_SUCCESS";
export const AUTO_TIME_READ_FAIL = "AUTO_TIME_READ_FAIL";
export const AUTO_TIME_READ_RESET = "AUTO_TIME_READ_RESET";

export const STOP_CORN_JOB_REQUEST = "STOP_CORN_JOB_REQUEST";
export const STOP_CORN_JOB_SUCCESS = "STOP_CORN_JOB_SUCCESS";
export const STOP_CORN_JOB_FAIL = "STOP_CORN_JOB_FAIL";
export const STOP_CORN_JOB_RESET = "STOP_CORN_JOB_RESET";

export const FOLLOW_MANGA_REQUEST = "FOLLOW_MANGA_REQUEST";
export const FOLLOW_MANGA_SUCCESS = "FOLLOW_MANGA_SUCCESS";
export const FOLLOW_MANGA_FAIL = "FOLLOW_MANGA_FAIL";
export const FOLLOW_MANGA_RESET = "FOLLOW_MANGA_RESET";

export const DELETE_FOLLOW_MANGA_REQUEST = "DELETE_FOLLOW_MANGA_REQUEST";
export const DELETE_FOLLOW_MANGA_SUCCESS = "DELETE_FOLLOW_MANGA_SUCCESS";
export const DELETE_FOLLOW_MANGA_FAIL = "DELETE_FOLLOW_MANGA_FAIL";
export const DELETE_FOLLOW_MANGA_RESET = "DELETE_FOLLOW_MANGA_RESET";

export const SEND_REQUEST_REQUEST = "SEND_REQUEST_REQUEST";
export const SEND_REQUEST_SUCCESS = "SEND_REQUEST_SUCCESS";
export const SEND_REQUEST_FAIL = "SEND_REQUEST_FAIL";
